---
- name: Install packages '{{ fpkg_package }}'
  shell: 'fastpkg -{{ fpkg_extra_args }}bp {{ fpkg_package }} install'
  register: shell_fastpkg_install
  failed_when:
    'shell_fastpkg_install.rc != 0
    or "Error:" in shell_fastpkg_install.stdout'
  changed_when: '"installed to" in shell_fastpkg_install.stdout'
  when: fpkg_install_dir == ""

- debug:
    msg: |
      '{{ shell_fastpkg_install.stdout }}'
      'Errors: {{ shell_fastpkg_install.stderr }}'
  when: servermonkey_debug and fpkg_install_dir == ""

- name: Install packages to specific location '{{ fpkg_package }}'
  shell: 'fastpkg -{{ fpkg_extra_args }}bp {{ fpkg_package }} install -{{ fpkg_extra_opts }}i {{ fpkg_install_dir }}'
  register: shell_fastpkg_install_dir
  failed_when:
    'shell_fastpkg_install_dir.rc != 0
    or "Error:" in shell_fastpkg_install_dir.stdout'
  changed_when: '"installed to" in shell_fastpkg_install_dir.stdout'
  when: fpkg_install_dir != ""

- debug:
    msg: 'Install packages to dir: {{ shell_fastpkg_install_dir.stdout }}'
  when: servermonkey_debug and fpkg_install_dir != ""