---
- name: Set file permissions (Posix)
  set_fact:
    fpkg_file_mode: 0644
  when: '"CYGWIN" not in ansible_os_family'

- name: Set file permissions (Windows)
  set_fact:
    fpkg_file_mode: 0755
  when: '"CYGWIN" in ansible_os_family'

- name: Export local cache
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  shell: 'fastpkg -b -p {{ fpkg_package }} exportcache'
  register: shell_fastpkg_export
  failed_when:
    'shell_fastpkg_export.rc != 0
    or shell_fastpkg_export.stdout == ""'
  changed_when: false
  become: false

- name: Save cache to remote
  copy:
    content: '{{ shell_fastpkg_export.stdout }}'
    dest: '{{ fpkg_file_repo_cache }}'
    mode: '{{ fpkg_file_mode }}'
  changed_when: false

- name: Find packages to copy
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  shell: "fastpkg -b -p {{ fpkg_package }} show -d"
  register: shell_fastpkg_offline
  failed_when:
    'shell_fastpkg_offline.rc != 0
    or "Download-Path is empty" in shell_fastpkg_offline.stdout_lines
    or "Error:" in shell_fastpkg_offline.stdout_lines'
  changed_when: false
  become: false

- debug:
    msg: 'Copy packages: {{ shell_fastpkg_offline.stdout }}'
  when: servermonkey_debug

- block:
    - name: Convert Windows to Posix downloads path
      shell: cygpath -u '{{ fpkg_path_downloads }}'
      register: fpkg_path_downloads_win
      changed_when: false

    - name: Set downloads path (Windows to Posix)
      set_fact:
        fpkg_path_downloads_final: "{{ fpkg_path_downloads_win.stdout }}/"
  when:
    '"CYGWIN" in ansible_os_family
    and ":" in fpkg_path_downloads'

- name: Set downloads path (Posix fallback)
  set_fact:
    fpkg_path_downloads_final: "{{ fpkg_path_downloads }}/"
  when:
    '":" not in fpkg_path_downloads'

- debug:
    msg: "New downloads path: {{ fpkg_path_downloads_final }}"
  when: servermonkey_debug

- name: Copy packages
  copy:
    src: '{{ item }}'
    remote_src: false
    dest: '{{ fpkg_path_downloads_final }}'
    mode: '{{ fpkg_file_mode }}'
  with_items: '{{ shell_fastpkg_offline.stdout_lines }}'
  when: shell_fastpkg_offline.stdout != ""