---
#info: Install fastpkg offline via Ansible host

# --- install fastpkg ---
- name: Repack fastpkg on Ansible host
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  script: repack-fastpkg.sh
  register: shell_fastpkg_install
  run_once: true
  become: false
  changed_when: "not 'skip' in shell_fastpkg_install.stdout"

- name: Copy fastpkg (Debian)
  copy:
    src: /tmp/fastpkg.deb
    dest: /tmp/fastpkg.deb
    mode: '0600'
  changed_when: false

- name: Install fastpkg (Debian)
  apt:
    deb: /tmp/fastpkg.deb
    install_recommends: true

- name: Check if dtrx is installed
  shell: command -v dtrx
  register: fastpkg_setup_dtrx_installed
  changed_when: false
  failed_when: false

- name: Install minimal dtrx
  block:
    - name: Install unarchivers for dtrx
      package:
        update_cache: yes
        name:
          - binutils
          - bzip2
          # 'cabextract' will be skipped because it is not on Debian DVD 1
          - cpio
          - lzma
          - p7zip-full
          - rpm
          - unzip
          - xz-utils
          # 'unshield' will be skipped because it is not on Debian DVD 1

    - name: Find package 'fastpkg-dtrx' in fastpkg repo
      connection: local
      vars:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      shell: fastpkg -qp fastpkg-dtrx show -d
      register: fastpkg_setup_dtrx_path
      become: false
      changed_when: false

    - name: Install dtrx (Posix)
      copy:
        src: "{{ fastpkg_setup_dtrx_path.stdout }}"
        dest: /usr/local/bin/dtrx
        mode: '0755'
        force: no

    - name: Make dtrx compatible with any Python version
      shell: |
        set -e
        DTRX="/usr/local/bin/dtrx"

        # skip if already set
        IN_USE=$(grep python <"$DTRX")
        if echo "$IN_USE" | grep -q python2; then
            echo "skip, already set to python2"
            exit 0
        elif echo "$IN_USE" | grep -q python3; then
            echo "skip, already set to python3"
            exit 0
        fi
        
        if [ -x "$(command -v python)" ]; then
            echo "skip, already compatible"
        elif [ -x "$(command -v python2)" ]; then
            echo "set to python2"
            sed -i 's|^#!/usr/bin/env python$|#!/usr/bin/env python2|' "$DTRX"
        elif [ -x "$(command -v python3)" ]; then
            echo "set to python3"
            sed -i 's|^#!/usr/bin/env python$|#!/usr/bin/env python3|' "$DTRX"
        else
            echo "Python is required"
            exit 1
        fi
      register: fastpkg_setup_dtrx_python
      changed_when: "not 'skip' in fastpkg_setup_dtrx_python.stdout"
  when: not fastpkg_setup_dtrx_installed.stdout